# Generated by Django 4.1.2 on 2022-11-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myconfessionmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tosendto', models.CharField(max_length=50)),
                ('facultyis', models.CharField(max_length=50)),
                ('confessionmsg', models.TextField()),
                ('youridentification', models.CharField(max_length=50)),
            ],
        ),
    ]
